### ISSUE TITLE
ImportError: cannot import name 'util' from 'ontology.utils'

### ISSUE THREAD

**Issue by kenneth** [punica-box/tutorialtoken-box#29]
```
Traceback (most recent call last):
  File "tutorial_token.py", line 10, in <module>
    from ontology.utils import util
ImportError: cannot import name 'util' from 'ontology.utils' (/usr/local/lib/python3.7/site-packages/ontology/utils/__init__.py)
```

**Comment by NashMiao** [comment]
@kenneth This is an compatibility issue. Can you help me? We need to update box's source code to fit newest `ontology-python-sdk`.

**Comment by NashMiao** [comment]
@kenneth sorry for delay. Now, this bug has been fixed. https://github.com/punica-box/tutorialtoken-box/commit/5446138a1a7dabbaf04de19692debf9fac469a8d
